
language: python

python:
  - "3.6"

before-script:
 - psql  -c "CREATE DATABASE users;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - coverage run -m pytest

after_success:
  - coveralls
