
language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
 - psql  -c "create database travis_ci_test;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - coverage run -m pytest

after_success:
  - coveralls
